### ISSUE TITLE
Number of valid and invalid examples should be the same

### ISSUE THREAD

**Issue by puredanger** [muhuk/validation-benchmark#18]
Currently the way the results are displayed it is natural to compare the "valid" and "invalid" pairs, however the number of examples included in each timing is different, so those are not meaningfully comparable as far as I can tell.  If they at least included the same number of examples, that might make things slightly better, although it's still hard to see what's actually packed into each timing.

**Comment by muhuk** [comment]
> those are not meaningfully comparable as far as I can tell

Right. And I think we just shouldn't compare `:valid` against `:invalid`.

> If they at least included the same number of examples, that might make things slightly better

I agree. But it still wouldn't be enough to compare `:valid`s and `:invalid`s IMO. I don't think `1:1` is the magic ratio, if there is one. In some cases it could be `20:1` or `3:1`, or maybe even `1:5`. Highly contextual.

My goal when picking inputs was to make sure implementations are not cheating. For example a list and a vector when we're just expecting a sequential collection. Or a list in invalid inputs when we're specifically expecting a vector. I didn't really pay attention to their counts. And I believe invalids are larger in some cases.

Perhaps this is also a bit related to #10. If we display absolute timings prominently, we would be emphasizing valid/invalid balance/imbalance.

If there is an objective, rational way to agree on a ratio `X`, I am willing to change the input sets. Worst case we can duplicate some inputs.

**Comment by puredanger** [comment]
I guess really what I want is more visibility into what a number on the output means. If I see 32000 ns, what does that timing include? Currently each number represents the aggregate of many kinds of work. That's kind of useful for big picture but kind of poor for decision-making.

**Comment by muhuk** [comment]
@puredanger are you wearing your library developer hat or are you a consumer trying to decide between alternatives?

**Comment by muhuk** [comment]
I am closing this because it seems the concern (although valid) is out of scope for this project.
