### ISSUE TITLE
bemch function/predicates specs

### ISSUE THREAD

**Issue by mpenet** [muhuk/validation-benchmark#20]
There should be a test for (anonymous) functions/predicates and signatures in general. Some libs provide very little for this (truss) others go pretty far (schema, spec). 
clj.spec might even trigger generative testing with c.spec/fspec so I would imagine this would provide interesting results.

**Comment by muhuk** [comment]
I think anything further than checking something is a function should be outside the scope of validation. But if you have some code, feel free to make a PR. I might change my mind.
